In [2]:
import pandas as pd

- opening a local csv file

In [6]:
df = pd.read_csv("./data/aug_train.csv")

- opening a csv file from url

In [8]:
import requests
from io import StringIO

In [13]:
url: str = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
data_request = requests.get(url=url)
data = StringIO(data_request.text)
pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [20]:
pd.read_csv('./data/file.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genres'])

        sno  name  release_year     rating  votes  genres
0         0    50             5  881250949    NaN     NaN
1         0   172             5  881250949    NaN     NaN
2         0   133             1  881250949    NaN     NaN
3       196   242             3  881250949    NaN     NaN
4       186   302             3  891717742    NaN     NaN
...     ...   ...           ...        ...    ...     ...
99998   880   476             3  880175444    NaN     NaN
99999   716   204             5  879795543    NaN     NaN
100000  276  1090             1  874795795    NaN     NaN
100001   13   225             2  882399156    NaN     NaN
100002   12   203             3  879959583    NaN     NaN

[100003 rows x 6 columns]

In [22]:
pd.read_csv("./data/aug_train.csv", index_col="enrollee_id")

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0